# Generate docs as markdown into a per-session tempdir that's automatically cleaned up when
# the R session terminates.
Rd2md::ReferenceManual(outdir = tempdir())

# Remove markdown package description
markdown_doc <- readLines(file.path(tempdir(), "Reference_Manual_qcflow.md"))
# Somewhat of a hack: find the second occurrence of "```", which delimits the TOC generated by
# Rd2md, and remove all preceding lines to delete the TOC.
toc_delimiter = "```"
first_function <- which(grepl(toc_delimiter, markdown_doc))[[2]] + 1
markdown_fixed <- markdown_doc[first_function:length(markdown_doc)]

# Remove function name from section
markdown_fixed <- gsub("# `[^`]+`:", "#", markdown_fixed)

# Remove description and usage headers
markdown_fixed <- gsub("## Description", "", markdown_fixed)
markdown_fixed <- gsub("## Usage", "", markdown_fixed)

# Remove objects exported from other packages section
last_section <- which(grepl("reexports", markdown_fixed))[[1]]
markdown_fixed <- markdown_fixed[1:last_section - 1]

# Write fixed markdown file
writeLines(markdown_fixed, "Reference_Manual_qcflow.md")

# Clear Sphinx docs and tree to correctly generate sections
if (dir.exists("../../../docs/build")) {
  unlink("../../../docs/build", recursive = TRUE)
}

# Generate reStructuredText documentation
rmarkdown::pandoc_convert("Reference_Manual_qcflow.md", output = "../../../docs/source/R-api.rst")

# Add R API header to RST docs
rst_header <- ".. _R-api:

========
R API
========

The QCFlow `R <https://www.r-project.org/about.html>`_ API allows you to use QCFlow :doc:`Tracking <tracking>`, :doc:`Projects <projects/>` and :doc:`Models <models/>`.

Prerequisites
=============

To use the QCFlow R API, you must install `the QCFlow Python package <https://pypi.org/project/qcflow/>`_.

.. code-block:: bash

    pip install qcflow

Installing with an Available Conda Environment example:

.. code-block:: bash
    
    conda create -n qcflow-env python
    conda activate qcflow-env
    pip install qcflow

The above provided commands create a new Conda environment named qcflow-env, specifying the default Python version. It then activates this environment, making it the active working environment. Finally, it installs the QCFlow package using pip, ensuring that QCFlow is isolated within this environment, allowing for independent Python and package management for QCFlow-related tasks.

Optionally, you can set the ``QCFLOW_PYTHON_BIN`` and ``QCFLOW_BIN`` environment variables to specify the Python and QCFlow binaries to use. By default, the R client automatically finds them using ``Sys.which('python')`` and ``Sys.which('qcflow')``.

.. code-block:: bash

    export QCFLOW_PYTHON_BIN=/path/to/bin/python
    export QCFLOW_BIN=/path/to/bin/qcflow

You can use the R API to start the `user interface <qcflow_ui_>`_, `create experiment <qcflow_create_experiment_>`_ and `search experiments <qcflow_search_experiments_>`_, `save models <qcflow_save_model.crate_>`_, `run projects <qcflow_run_>`_ and `serve models <qcflow_rfunc_serve_>`_ among many other functions available in the R API.

.. contents:: Table of Contents
    :local:
    :depth: 1
"
rst_doc <- readLines("../../../docs/source/R-api.rst")
# Convert non-breaking spaces inserted by pandoc to regular spaces
rst_doc <- gsub("\302\240", " ", rst_doc)
rst_doc <- c(rst_header, rst_doc)
writeLines(rst_doc, "../../../docs/source/R-api.rst")

# Generate docs by using an qcflow virtualenv and running `make` from `qcflow/docs`
