QCFLOW_DEPLOYMENTS_HEALTH_ENDPOINT = "/health"
QCFLOW_DEPLOYMENTS_CRUD_ENDPOINT_BASE = "/api/2.0/endpoints/"
QCFLOW_DEPLOYMENTS_LIMITS_BASE = "/api/2.0/endpoints/limits/"
QCFLOW_DEPLOYMENTS_ENDPOINTS_BASE = "/endpoints/"
QCFLOW_DEPLOYMENTS_QUERY_SUFFIX = "/invocations"
QCFLOW_DEPLOYMENTS_LIST_ENDPOINTS_PAGE_SIZE = 3000
