# Build an image that can serve qcflow models.
FROM python:${{ PYTHON_VERSION }}-slim

RUN apt-get -y update && apt-get install -y --no-install-recommends nginx



WORKDIR /opt/qcflow

# Install QCFlow from local source
COPY qcflow-project /opt/qcflow
RUN pip install /opt/qcflow

# Copy model to image and install dependencies
COPY model_dir/model /opt/ml/model
RUN python -c "from qcflow.models import container as C; C._install_pyfunc_deps('/opt/ml/model', install_qcflow=False, enable_mlserver=False, env_manager='local');"

ENV QCFLOW_DISABLE_ENV_CREATION=True
ENV ENABLE_MLSERVER=False
ENV GUNICORN_CMD_ARGS="--timeout 60 -k gevent"

# granting read/write access and conditional execution authority to all child directories
# and files to allow for deployment to AWS Sagemaker Serverless Endpoints
# (see https://docs.aws.amazon.com/sagemaker/latest/dg/serverless-endpoints.html)
RUN chmod o+rwX /opt/qcflow/

# clean up apt cache to reduce image size
RUN rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["python", "-c", "from qcflow.models import container as C; C._serve('local')"]
