name: Feature Request
description: Use this template for feature and enhancement proposals.
labels: "enhancement"
title: "[FR]"

body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a feature request. **Before proceeding, please review QCFlow's [Issue Policy for feature requests](https://www.github.com/qcflow/qcflow/blob/master/ISSUE_POLICY.md#feature-requests) and the [QCFlow Contributing Guide](https://github.com/qcflow/qcflow/blob/master/CONTRIBUTING.md)**.
        **Please fill in this feature request template to ensure a timely and thorough response.**
  - type: dropdown
    id: contribution
    attributes:
      label: Willingness to contribute
      description: The QCFlow Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature (either as an QCFlow Plugin or an enhancement to the QCFlow code base)?
      options:
        - Yes. I can contribute this feature independently.
        - Yes. I would be willing to contribute this feature with guidance from the QCFlow community.
        - No. I cannot contribute this feature at this time.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal Summary
      description: |
        In a few sentences, provide a clear, high-level description of the feature request
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: |
        - What is the use case for this feature?
        - Why is this use case valuable to support for QCFlow users in general?
        - Why is this use case valuable to support for your project(s) or organization?
        - Why is it currently difficult to achieve this use case? (please be as specific as possible about why related QCFlow features and components are insufficient)
      value: |
        > #### What is the use case for this feature?

        > #### Why is this use case valuable to support for QCFlow users in general?

        > #### Why is this use case valuable to support for your project(s) or organization?

        > #### Why is it currently difficult to achieve this use case?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Details
      description: |
        Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing Guide](https://github.com/qcflow/qcflow/blob/master/CONTRIBUTING.md#contribution-guidelines).
    validations:
      required: false
  - type: checkboxes
    id: component
    attributes:
      label: What component(s) does this bug affect?
      description: Please choose one or more components below.
      options:
        - label: "`area/artifacts`: Artifact stores and artifact logging"
          required: false
        - label: "`area/build`: Build and test infrastructure for QCFlow"
          required: false
        - label: "`area/deployments`: QCFlow Deployments client APIs, server, and third-party Deployments integrations"
          required: false
        - label: "`area/docs`: QCFlow documentation pages"
          required: false
        - label: "`area/examples`: Example code"
          required: false
        - label: "`area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry"
          required: false
        - label: "`area/models`: MLmodel format, model serialization/deserialization, flavors"
          required: false
        - label: "`area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates"
          required: false
        - label: "`area/projects`: MLproject format, project running backends"
          required: false
        - label: "`area/scoring`: QCFlow Model server, model deployment tools, Spark UDFs"
          required: false
        - label: "`area/server-infra`: QCFlow Tracking server backend"
          required: false
        - label: "`area/tracking`: Tracking Service, tracking client APIs, autologging"
          required: false
  - type: checkboxes
    id: interface
    attributes:
      description: Please choose one or more interfaces below.
      label: What interface(s) does this bug affect?
      options:
        - label: "`area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server"
          required: false
        - label: "`area/docker`: Docker use across QCFlow's components, such as QCFlow Projects and QCFlow Models"
          required: false
        - label: "`area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry"
          required: false
        - label: "`area/windows`: Windows support"
          required: false
  - type: checkboxes
    id: language
    attributes:
      description: Please choose one or more languages below.
      label: What language(s) does this bug affect?
      options:
        - label: "`language/r`: R APIs and clients"
          required: false
        - label: "`language/java`: Java APIs and clients"
          required: false
        - label: "`language/new`: Proposals for new client languages"
          required: false
  - type: checkboxes
    id: integration
    attributes:
      description: Please choose one or more cloud integrations below.
      label: What integration(s) does this bug affect?
      options:
        - label: "`integrations/azure`: Azure and Azure ML integrations"
          required: false
        - label: "`integrations/sagemaker`: SageMaker integrations"
          required: false
        - label: "`integrations/databricks`: Databricks integrations"
          required: false
