name: Installation Issues
description: Use this template for reporting bugs encountered while installing QCFlow.
labels: "bug"
title: "[SETUP-BUG]"

body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/qcflow/qcflow/blob/master/ISSUE_POLICY.md) for information on what types of issues we address.
        **Please fill in this installation issue template to ensure a timely and thorough response.**
  - type: textarea
    attributes:
      label: System information
      description: |
        Describe the system where you encountered the installation issue.
      value: |
        - **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
        - **QCFlow installed from (source or binary)**:
        - **QCFlow version (run ``qcflow --version``)**:
        - **Python version**:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Code to reproduce issue
      description: |
        Provide a reproducible test case that is the bare minimum necessary to generate the problem.
      placeholder: |
        ```bash
        pip install qcflow=x.y.z
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the problem
      description: |
        Provide the exact sequence of commands / steps that you executed before running into the problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other info / logs
      description: |
        Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
      placeholder: |
        ```
        ERROR: Could not find a version that satisfies the requirement qcflow==x.y.z
        ```
    validations:
      required: false
