version: "3"
services:
  qcflow:
    image: "ghcr.io/qcflow/qcflow-devcontainer"
    working_dir: /workspaces/qcflow
    environment:
      QCFLOW_HOME: /workspaces/qcflow
      QCFLOW_TRACKING_URI: sqlite:////workspaces/qcflow/mlruns.db
    volumes:
      - $PWD:/workspaces/qcflow
      - build:/workspaces/qcflow/qcflow/server/js/build

volumes:
  build:
